<?php



    // function getMockEn() {
    //     return array("THE SEARCH FOR LORNA", 
    //     'Daisy Hamilton was a private detective. ', 
    //     'She was thirty years old and had been a detective for the past two years. ', 
    //     'Every morning she went to her office to wait for phone calls or open the door to clients needing her services.', 
    //     "Daisy wasn't very well known yet but occasionally people telephoned her from the advertisement she had put in the local newspaper.", 
    //     "One morning at about eleven o'clock someone knocked on her office door. ", 
    //     'It was a fat lady who wore a fur around her neck.', 
    //     '"Hello, can I help you?" Daisy asked the lady. "Please come and sit down."', 
    //     '"Oh yes indeed! I need your help desperately. ', 
    //     'Lorna, my little one has disappeared. I don\'t know what to do."', 
    //     'Daisy offered the fat lady a cup of instant coffee and awaited the details. ', 
    //     "The fat lady sat down heavily and put her large red leather handbag on Daisy's desk.", 
    //     '"Please tell me everything - Mrs. ...?"', 
    //     '"Mrs. Edwina Humphries is my name. I am afraid they will ask me for money - I\'m afraid Lorna has been kidnapped!"', 
    //     '"That\'s terrible, Mrs. Humphries. Does Mr. Humphries, too, think Lorna has been kidnapped?"', 
    //     '"My husband is not interested if Lorna has been kidnapped or not!"', 
    //     '"Really, Mrs. Humphries? But is your husband Lorna\'s real father?"', 
    //     '"I don\'t know what you mean. We bought Lorna together," replied Mrs. Humphries.', 
    //     '"You bought ............Mrs. Humphries, that\'s illegal, you know."', 
    //     '"No it isn\'t, not in India!"', 
    //     '"You bought Lorna in India?"', 
    //     'Yes indeed! And she always keeps me great company, you know." ', 
    //     '"Mrs. Humphries opened her huge leather bag to pull out a handkerchief.', 
    //     'With horror Daisy saw a wiggling creature come out of that bag.', 
    //     '"Mrs. Humphries - move that away immediately!" screamed Daisy.', 
    //     '"What? Oh Lorna - I\'ve found you at last!" said Mrs. Humphries. "You hid in my bag - you naughty girl!"', 
    //     '"Mrs. Humphries. This is Lorna?"', 
    //     'Yes, our Bengali swamp snake. Oh thank you my dear. No, I don\'t think I need your services any longer!"', 
    //     'As Daisy shut the door after Mrs. Humphries, she made a mental note to write in the advertisement: no animals, no snakes.'            );
    // }

    // function getMockFr(){
    //     return  array("LA RECHERCHE DE LORNA",
    //     'Daisy Hamilton était détective privée.', 
    //     'Elle avait trente ans, et avait été détective durant les deux années précédentes.', 
    //     'Chaque matin elle allait à son bureau, pour attendre des appels téléphoniques ou ouvrir sa porte à des clients  ayant besoin de ses services.', 
    //     "Daisy n'était pas encore très bien connue, mais parfois des gens lui téléphonaient suite à la publicité qu'elle avait placée dans le journal local. ", 
    //     "Un matin vers onze heures quelqu'un frappa à la porte de son bureau.", 
    //     "C'était une dame forte qui portait une fourrure autour du cou.", 
    //     '"Hello, puis-je vous aider ?" demanda Daisy à la dame. "Entrez s\'il vous plaît, et asseyez-vous."', 
    //     '"Oh oui bien sûr ! J\'ai besoin désespérément de votre aide.', 
    //     'Lorna, ma petite, a disparu. Je ne sais pas quoi faire."', 
    //     'Daisy offrit à la dame forte une tasse de café instantané et attendit les détails.', 
    //     "La dame forte s'assit lourdement et posa son gros sac à main en cuir rouge sur le bureau de Daisy.", 
    //     '"S\'il vous plaît dites-moi tout - Mme … ?"', 
    //     '"Je m\'appelle Mme Edwina Humphries. Je crains qu\'ils me réclament une rançon - J\'ai peur que Lorna ait été kidnappée !"', 
    //     '"C\'est terrible, Mme Humphries. Est-ce que M. Humphries pense, lui aussi, que Lorna a été kidnappée ?"', 
    //     '"Mon mari n\'est pas intéressé par le fait que Lorna ait ou non été kidnappée !"', 
    //     '"Vraiment, Mme Humphries ? Mais votre mari est-il le vrai père de Lorna ?"', 
    //     '"Je ne comprends pas ce que vous voulez dire. Nous avons acheté Lorna ensemble," répondit Mme Humphries.', 
    //     '"Vous avez acheté …….. Mme Humphries, c\'est illégal, vous savez."', 
    //     '"Non ça ne l\'est pas, pas aux Indes !"', 
    //     '"Vous avez acheté Lorna aux Indes ?"', 
    //     '"Oui bien sûr. Et elle me tient toujours bien compagnie, vous savez."', 
    //     'Mme Humphries ouvrit son énorme sac de cuir pour en sortir un mouchoir.', 
    //     'Horrifiée Daisy vit une créature ondulante sortir de ce sac.', 
    //     '"Mme Humphries - enlevez ça immédiatement !" hurla Daisy.', 
    //     '"Quoi ? Oh Lorna\xa0 - je t\'ai enfin trouvée !" dit Mme Humphries. "Tu te cachais dans mon sac, vilaine fille !"', 
    //     '"Mme Humphries, c\'est ça Lorna ?"', 
    //     '"Oui, c\'est notre serpent des marais du Bengale. Oh merci ma chère. Non, je ne crois pas avoir besoin de vos services plus longtemps !"', 
    //     "Tout en refermant la porte derrière Mme Humphries, Daisy nota mentalement d'écrire dans son annonce : pas d'animaux, pas de serpents.");
    // }

    // function getMockDe(){
    //     return array( "Die Suche nach Lorna",
    //     'Daisy Hamilton war Privatdetektivin.', 
    //     'Sie war dreissig Jahre alt und arbeitete seit zwei Jahren in diesem Beruf.', 
    //     'Jeden Morgen ging sie in ihr Büro und wartete darauf, dass das Telefon klingeln oder ein potentieller Klient zur Tür hereinkommen würde.', 
    //     'Daisy hatte noch keinen großen Namen, aber hin und wieder meldeten sich Leute auf ihre Anzeige in der Lokalzeitung hin.', 
    //     'Eines Morgens so gegen elf klopfte jemand an ihre Bürotür.', 
    //     'Es war eine dicke Dame mit einer Pelzstola.', 
    //     '"Hallo, kann ich Ihnen helfen?" fragte Daisy die Dame.', 
    //     '"O ja, wirklich! Ich brauche dringend Ihre Hilfe.', 
    //     'Meine kleine Lorna ist verschwunden. Ich weiß nicht, was ich tun soll."', 
    //     'Daisy bot der dicken Dame eine Tasse Instantkaffee an und wartete auf die Details.', 
    //     'Die dicke Dame setzte sich schwerfällig hin und stellte ihre große rote Handtasche auf Daisys Pult.', 
    //     '"Bitte erzählen Sie mir alles, Mrs. .....?"', 
    //     '"Ich heiße Edwina Humphries. Ich fürchte, die werden Geld wollen – ich fürchte, Lorna wurde entführt!"', 
    //     '"Das ist ja furchtbar, Mrs. Humphries. Glaubt Mr. Humphries auch, Lorna sei entführt worden?"', 
    //     '"Meinen Mann kümmert es nicht, ob Lorna entführt wurde oder nicht!"', 
    //     '"Wirklich, Mrs. Humphries?\xa0 Ist Mr. Humphries denn Lornas leiblicher Vater?"', 
    //     '"Ich weiß nicht, was Sie meinen. Wir haben Lorna zusammen gekauft", antwortete Mrs. Humphries.', 
    //     '"Gekauft... Sie wissen aber, dass das illegal ist, Mrs. Humphries."', 
    //     '"Nein, ist es nicht, nicht in Indien!"', 
    //     '"Sie haben Lorna in Indien gekauft?"', 
    //     '"Ja natürlich. Und sie leistet mir immer so gut Gesellschaft, wissen Sie."', 
    //     'Mrs. Humphries öffnete ihre riesige Ledertasche und zog ihr Taschentuch heraus.', 
    //     'Daisy beobachtete mit Entsetzen, wie etwas aus der Tasche herausschlängelte.', 
    //     '"Mrs. Humphries – nehmen Sie das sofort weg!" kreischte Daisy.', 
    //     '"Was? O Lorna, endlich habe ich dich gefunden!" sagte Mrs. Humphries. Du hast dich in meiner Tasche versteckt, du böses Mädchen!"', 
    //     '"Mrs. Humphries – das ist Lorna?"', 
    //     '"Ja, unsere bengalische Sumpfschlange. Oh, ich danke Ihnen, meine Liebe, aber ich glaube, ich benötige Ihre Dienste nicht mehr!"', 
    //     'Während Daisy die Tür hinter Mrs. Humphries schloss, nahm sie sich in Gedanken vor, ihre Anzeige zu ergänzen: Keine Tiere, keine Schlangen.');
    // }
    